export const opciones = [
	{ id: 1, descripcion: "Company size" },
	{ id: 2, descripcion: "Industries" },
	{ id: 3, descripcion: "Service or product you offer" },
	{ id: 4, descripcion: "Founding date of the company" },
	{ id: 5, descripcion: "Total founding amount" },
	{ id: 6, descripcion: "Traffic web" },
	{ id: 7, descripcion: "Number of founding rounds" },
	{ id: 8, descripcion: "Social Media Presence" },
	{ id: 9, descripcion: "Number of technologies" },
	{ id: 10, descripcion: "Growth of the company" },
	{ id: 11, descripcion: "Technology spend" },
];

/*
	
*/
export const filtros = [
	{ idopcion: 1, id: 1, descripcion: "1 - 10" },
	{ idopcion: 1, id: 2, descripcion: "11 - 50" },
	{ idopcion: 1, id: 3, descripcion: "51 - 200" },
	{ idopcion: 1, id: 4, descripcion: "201 - 500" },
	{ idopcion: 1, id: 5, descripcion: "501 - 1000" },
	{ idopcion: 1, id: 6, descripcion: "1001 - 5000" },
	{ idopcion: 1, id: 7, descripcion: "5001 - 10000" },
	{ idopcion: 1, id: 8, descripcion: "+ 10000" },

	{ idopcion: 2, id: 1, descripcion: "Administrative services" },
	{ idopcion: 2, id: 2, descripcion: "Advertising" },
	{ idopcion: 2, id: 3, descripcion: "Agriculture and Farming" },
	{ idopcion: 2, id: 4, descripcion: "Apps" },
	{ idopcion: 2, id: 5, descripcion: "Artificial Intelligence" },
	{ idopcion: 2, id: 6, descripcion: "Biotechnology" },
	{ idopcion: 2, id: 7, descripcion: "Clothing and Apparel" },
	{ idopcion: 2, id: 8, descripcion: "Commerce and shopping" },
	{ idopcion: 2, id: 9, descripcion: "Community and lifestyle" },
	{ idopcion: 2, id: 10, descripcion: "Consumer electronics" },
	{ idopcion: 2, id: 11, descripcion: "Consumer goods" },
	{ idopcion: 2, id: 12, descripcion: "Content and publishing" },
	{ idopcion: 2, id: 13, descripcion: "Data and Analytics" },
	{ idopcion: 2, id: 14, descripcion: "Design" },
	{ idopcion: 2, id: 15, descripcion: "Education" },
	{ idopcion: 2, id: 16, descripcion: "Energy" },
	{ idopcion: 2, id: 17, descripcion: "Events" },
	{ idopcion: 2, id: 18, descripcion: "Financial services" },
	{ idopcion: 2, id: 19, descripcion: "Food and beverage" },
	{ idopcion: 2, id: 20, descripcion: "Gaming" },
	{ idopcion: 3, id: 1, descripcion: "TextoLibre" },
	{ idopcion: 4, id: 1, descripcion: "Less than 1 year" },
	{ idopcion: 4, id: 2, descripcion: "Between 1 and 2 years" },
	{ idopcion: 4, id: 3, descripcion: "Between 3 and 5 years" },
	{ idopcion: 4, id: 4, descripcion: "Between 6 and 10 years" },
	{ idopcion: 4, id: 5, descripcion: "More than 10 years" },

	{ idopcion: 5, id: 1, descripcion: "Texto" },
	{ idopcion: 6, id: 1, descripcion: "Texto" },
	{ idopcion: 7, id: 1, descripcion: "TextoBetw" },
	{ idopcion: 8, id: 1, descripcion: "Instagram" },
	{ idopcion: 8, id: 2, descripcion: "Twitter" },
	{ idopcion: 8, id: 3, descripcion: "Linkedin" },
	{ idopcion: 8, id: 4, descripcion: "Facebook" },
	{ idopcion: 8, id: 5, descripcion: "Pinterest" },
	{ idopcion: 8, id: 6, descripcion: "Otros" },
	{ idopcion: 9, id: 1, descripcion: "TextoLibre" },
	{ idopcion: 10, id: 1, descripcion: "Texto" },
	{ idopcion: 11, id: 1, descripcion: "Texto" },

];

export const countries = [
	
	{name: 'Afghanistan', code: 'AF'}, 
	{name: 'Åland Islands', code: 'AX'}, 
	{name: 'Albania', code: 'AL'}, 
	{name: 'Algeria', code: 'DZ'}, 
	{name: 'American Samoa', code: 'AS'}, 
	{name: 'AndorrA', code: 'AD'}, 
	{name: 'Angola', code: 'AO'}, 
	{name: 'Anguilla', code: 'AI'}, 
	{name: 'Antarctica', code: 'AQ'}, 
	{name: 'Antigua and Barbuda', code: 'AG'}, 
	{name: 'Argentina', code: 'AR'}, 
	{name: 'Armenia', code: 'AM'}, 
	{name: 'Aruba', code: 'AW'}, 
	{name: 'Australia', code: 'AU'}, 
	{name: 'Austria', code: 'AT'}, 
	{name: 'Azerbaijan', code: 'AZ'}, 
	{name: 'Bahamas', code: 'BS'}, 
	{name: 'Bahrain', code: 'BH'}, 
	{name: 'Bangladesh', code: 'BD'}, 
	{name: 'Barbados', code: 'BB'}, 
	{name: 'Belarus', code: 'BY'}, 
	{name: 'Belgium', code: 'BE'}, 
	{name: 'Belize', code: 'BZ'}, 
	{name: 'Benin', code: 'BJ'}, 
	{name: 'Bermuda', code: 'BM'}, 
	{name: 'Bhutan', code: 'BT'}, 
	{name: 'Bolivia', code: 'BO'}, 
	{name: 'Bosnia and Herzegovina', code: 'BA'}, 
	{name: 'Botswana', code: 'BW'}, 
	{name: 'Bouvet Island', code: 'BV'}, 
	{name: 'Brazil', code: 'BR'}, 
	{name: 'British Indian Ocean Territory', code: 'IO'}, 
	{name: 'Brunei Darussalam', code: 'BN'}, 
	{name: 'Bulgaria', code: 'BG'}, 
	{name: 'Burkina Faso', code: 'BF'}, 
	{name: 'Burundi', code: 'BI'}, 
	{name: 'Cambodia', code: 'KH'}, 
];

export const idioms = [
	{ id: 1, descripcion: "Chinese" },
	{ id: 2, descripcion: "Czech" },
	{ id: 3, descripcion: "Danish" },
	{ id: 4, descripcion: "Dutch" },
	{ id: 5, descripcion: "English" },
	{ id: 6, descripcion: "French" },
	{ id: 7, descripcion: "German" },
	{ id: 8, descripcion: "Italian" },
	{ id: 9, descripcion: "Korean" },
	{ id: 10, descripcion: "Spanish" },
	{ id: 11, descripcion: "Turkmen" },
];